version: "3.8"

services:
  # Development service with hot reload
  nextjs-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    profiles:
      - dev

  # Production service (for testing production builds locally)
  nextjs-prod:
    build: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - redis
    profiles:
      - prod

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
