packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: 19.2.4
  react-dom: 19.2.4
  react-hook-form: ^7.56.4
  sonner: ^2.0.3
  zod: ^3.25.36
  next: 16.1.6
  '@types/react': 19.2.13
  '@types/react-dom': 19.2.3
  '@types/node': ^20.17.32
  typescript: ^5.8.3
  eslint: ^9.25.1
  tailwindcss: ^4.1.4
  '@tailwindcss/postcss': ^4.1.4
  '@tailwindcss/typography': ^0.5.16
  '@hookform/resolvers': ^5.0.1
  'lucide-react': ^0.511.0
  'clsx': ^2.1.1
  'class-variance-authority': ^0.7.1
  'tailwind-merge': ^3.3.0
  '@trpc/client': ^11.10.0
  '@trpc/react-query': ^11.10.0
  '@trpc/server': ^11.10.0
  '@tanstack/react-query': ^5.69.0
  'superjson': ^2.2.1
  'next-intl': ^4.1.0
  '@modelcontextprotocol/sdk': 1.25.3
  'mcp-handler': ^1.0.7
  'vitest': ^4.0.18
  '@testcontainers/redis': ^11.12.0
  'testcontainers': ^11.12.0
  '@playwright/test': ^1.58.2
  'postcss': ^8.5.3
  'server-only': ^0.0.1
  'nanoid': ^5.1.5
  'redis': ^4.7.0
  'sharp': ^0.34.4
  '@t3-oss/env-nextjs': ^0.12.0
  '@dnd-kit/core': ^6.3.1
  '@dnd-kit/utilities': ^3.2.2
  '@dnd-kit/sortable': ^10.0.0
  '@eslint/eslintrc': ^3.3.1
  'prettier': ^3.5.3
  'prettier-plugin-tailwindcss': ^0.6.11
  'eslint-config-next': ^15.3.3
  'react-country-flag': ^3.1.0
  'gray-matter': ^4.0.3
  'tw-animate-css': ^1.3.1
  'typescript-eslint': ^8.27.0
