packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  react: 19.2.4
  react-dom: 19.2.4
  next: 16.1.6
  '@types/react': 19.2.13
  '@types/react-dom': 19.2.3
  '@types/node': ^20.17.32
  typescript: ^5.8.3
  eslint: ^9.25.1
  tailwindcss: ^4.1.4
  '@tailwindcss/postcss': ^4.1.4
  '@tailwindcss/typography': ^0.5.16
