/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    categories: Category;
    'content-opportunities': ContentOpportunity;
    guides: Guide;
    'landing-pages': LandingPage;
    media: Media;
    'page-audits': PageAudit;
    pages: Page;
    services: Service;
    users: User;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'content-opportunities': ContentOpportunitiesSelect<false> | ContentOpportunitiesSelect<true>;
    guides: GuidesSelect<false> | GuidesSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'page-audits': PageAuditsSelect<false> | PageAuditsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'nl') | ('en' | 'nl')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'nl';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  slug: string;
  title: string;
  description: string;
  /**
   * Lucide icon name (e.g. mail, folder, search)
   */
  icon: string;
  /**
   * Category body text shown on the category page
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Custom page title for search engines (50-60 chars)
   */
  metaTitle?: string | null;
  /**
   * Custom meta description for search engines (150-160 chars)
   */
  metaDescription?: string | null;
  /**
   * Target SEO keywords (localized — different keywords per market)
   */
  keywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Open Graph title for social sharing
   */
  ogTitle?: string | null;
  /**
   * Open Graph description for social sharing
   */
  ogDescription?: string | null;
  /**
   * Open Graph image for social sharing
   */
  ogImage?: (number | null) | Media;
  /**
   * AI-assessed SEO quality score (0-100)
   */
  seoScore?: number | null;
  /**
   * Notes from last SEO review
   */
  seoNotes?: string | null;
  /**
   * When SEO was last reviewed
   */
  lastSeoReviewAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Content backlog discovered by opportunity-finder. Type discriminator distinguishes demand-driven (GSC) vs supply-driven (Reddit/SERP) finds. Operational data — no drafts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-opportunities".
 */
export interface ContentOpportunity {
  id: number;
  type: 'missing-guide' | 'missing-service' | 'almost-ranking' | 'new-category';
  priority: 'high' | 'medium' | 'low';
  status: 'new' | 'reviewed' | 'queued' | 'written' | 'rejected';
  discoveredAt: string;
  title: string;
  /**
   * Lowercase canonical query this opportunity targets.
   */
  targetKeyword: string;
  locale?: ('en' | 'nl' | 'both') | null;
  estimatedMonthlyImpressions?: number | null;
  reasoning: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  competitorUrls?:
    | {
        url: string;
        title?: string | null;
        rank?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * GSC rows that triggered this opportunity (Mode A).
   */
  sourceQueries?:
    | {
        query: string;
        impressions?: number | null;
        position?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Reddit posts that triggered this opportunity (Mode B).
   */
  redditSignals?:
    | {
        subreddit: string;
        postUrl: string;
        snippet?: string | null;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Set once an opportunity has been acted on.
   */
  resultingType?: ('service' | 'guide') | null;
  /**
   * The service created from this opportunity (when resultingType = service).
   */
  resultingService?: (number | null) | Service;
  /**
   * The guide created from this opportunity (when resultingType = guide).
   */
  resultingGuide?: (number | null) | Guide;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  slug: string;
  region: 'eu' | 'non-eu' | 'eu-friendly';
  featured?: boolean | null;
  /**
   * Tracks progress through the content pipeline (write → humanize → SEO → translate)
   */
  contentPipelineStatus?:
    | ('not-started' | 'in-progress' | 'written' | 'humanized' | 'seo-checked' | 'translated' | 'complete')
    | null;
  name: string;
  category: number | Category;
  /**
   * Country where the service is based
   */
  location: string;
  freeOption?: boolean | null;
  startingPrice?: string | null;
  /**
   * Short description shown in cards and search results
   */
  description: string;
  /**
   * Service website URL
   */
  url: string;
  /**
   * Affiliate/referral link. When set, outbound buttons use this instead of the direct URL.
   */
  affiliateUrl?: string | null;
  screenshot?: (number | null) | Media;
  logo?: (number | null) | Media;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Structured pricing plans for the pricing subpage
   */
  pricingTiers?:
    | {
        name: string;
        price: string;
        billingNote?: string | null;
        features?:
          | {
              feature: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Main service body content
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Privacy/data concerns (non-EU services only)
   */
  issues?:
    | {
        issue: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Recommended EU alternative (non-EU services only)
   */
  recommendedAlternative?: (number | null) | Service;
  /**
   * Current status of research for this service
   */
  researchStatus?: ('not-started' | 'in-progress' | 'needs-update' | 'complete') | null;
  /**
   * When this service was last researched
   */
  lastResearchedAt?: string | null;
  /**
   * GDPR compliance status
   */
  gdprCompliance?: ('compliant' | 'partial' | 'non-compliant' | 'unknown') | null;
  /**
   * Consumer-friendly summary of GDPR stance and data practices (localized, rewritten by /write skill)
   */
  gdprNotes?: string | null;
  /**
   * Link to the service's privacy policy
   */
  privacyPolicyUrl?: string | null;
  /**
   * Detailed pricing breakdown (tiers, limits, enterprise pricing)
   */
  pricingDetails?: string | null;
  /**
   * Link to the service's pricing page
   */
  pricingUrl?: string | null;
  /**
   * More specific than the "location" field — include city (e.g. "Berlin, Germany")
   */
  headquarters?: string | null;
  /**
   * Parent company or organization, if applicable
   */
  parentCompany?: string | null;
  /**
   * Year the service was founded
   */
  foundedYear?: number | null;
  /**
   * Approximate employee count or range (e.g. "50-200")
   */
  employeeCount?: string | null;
  /**
   * Countries/regions where user data is stored
   */
  dataStorageLocations?:
    | {
        location: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Security certifications (ISO 27001, SOC 2, HIPAA, etc.)
   */
  certifications?:
    | {
        certification: string;
        id?: string | null;
      }[]
    | null;
  openSource?: boolean | null;
  /**
   * Link to source code repository (if open source)
   */
  sourceCodeUrl?: string | null;
  /**
   * General research notes, competitive analysis, AI-generated summaries
   */
  researchNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * URLs used as sources for research
   */
  sourceUrls?:
    | {
        url: string;
        /**
         * Source description (e.g. "Official blog post")
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Aggregated Reddit sentiment. Populated by the research skill — don't edit by hand.
   */
  userSentiment?: {
    positive?: number | null;
    negative?: number | null;
    mixed?: number | null;
    /**
     * Consumer-facing 2-3 sentence summary of what users say on Reddit.
     */
    summary?: string | null;
    lastUpdated?: string | null;
  };
  /**
   * Raw Reddit posts that fed userSentiment. Source data, not localized.
   */
  redditMentions?:
    | {
        subreddit: string;
        postUrl: string;
        postTitle?: string | null;
        sentiment?: ('positive' | 'negative' | 'mixed' | 'neutral') | null;
        snippet?: string | null;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * News coverage in the last 12 months. Populated by the research skill.
   */
  recentNews?:
    | {
        source: string;
        url: string;
        title?: string | null;
        date?: string | null;
        /**
         * 1-sentence consumer-facing summary of the article.
         */
        summary?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Custom page title for search engines (50-60 chars)
   */
  metaTitle?: string | null;
  /**
   * Custom meta description for search engines (150-160 chars)
   */
  metaDescription?: string | null;
  /**
   * Target SEO keywords (localized — different keywords per market)
   */
  keywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Open Graph title for social sharing
   */
  ogTitle?: string | null;
  /**
   * Open Graph description for social sharing
   */
  ogDescription?: string | null;
  /**
   * Open Graph image for social sharing
   */
  ogImage?: (number | null) | Media;
  /**
   * AI-assessed SEO quality score (0-100)
   */
  seoScore?: number | null;
  /**
   * Notes from last SEO review
   */
  seoNotes?: string | null;
  /**
   * When SEO was last reviewed
   */
  lastSeoReviewAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides".
 */
export interface Guide {
  id: number;
  slug: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  /**
   * e.g. "45 minutes"
   */
  timeRequired: string;
  date?: string | null;
  /**
   * Feature this guide as the homepage hero poster. Only one guide should be flagged at a time; the most recent published guide is used as a fallback.
   */
  featuredOnHomepage?: boolean | null;
  /**
   * Tracks progress through the content pipeline
   */
  contentPipelineStatus?:
    | ('not-started' | 'in-progress' | 'written' | 'humanized' | 'seo-checked' | 'translated' | 'complete')
    | null;
  title: string;
  category: number | Category;
  description: string;
  /**
   * The non-EU service being migrated from
   */
  sourceService: number | Service;
  /**
   * The EU service being migrated to
   */
  targetService: number | Service;
  author?: string | null;
  /**
   * Features missing in the target service compared to the source
   */
  missingFeatures?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Introduction section — why switch?
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Prerequisites and what you need before starting
   */
  beforeYouStart?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ordered migration steps
   */
  steps?:
    | {
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Optional video for this step
         */
        video?: (number | null) | Media;
        videoOrientation?: ('landscape' | 'portrait') | null;
        /**
         * Whether this step is fully written (progress tracking)
         */
        complete?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Common issues and their solutions
   */
  troubleshooting?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Conclusion and next steps
   */
  outro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Custom page title for search engines (50-60 chars)
   */
  metaTitle?: string | null;
  /**
   * Custom meta description for search engines (150-160 chars)
   */
  metaDescription?: string | null;
  /**
   * Target SEO keywords (localized — different keywords per market)
   */
  keywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Open Graph title for social sharing
   */
  ogTitle?: string | null;
  /**
   * Open Graph description for social sharing
   */
  ogDescription?: string | null;
  /**
   * Open Graph image for social sharing
   */
  ogImage?: (number | null) | Media;
  /**
   * AI-assessed SEO quality score (0-100)
   */
  seoScore?: number | null;
  /**
   * Notes from last SEO review
   */
  seoNotes?: string | null;
  /**
   * When SEO was last reviewed
   */
  lastSeoReviewAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: number;
  slug: string;
  title: string;
  description: string;
  category?: (number | null) | Category;
  /**
   * EU services to recommend on this page
   */
  recommendedServices?: (number | Service)[] | null;
  /**
   * The non-EU service this landing page targets
   */
  relatedService?: (number | null) | Service;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Custom page title for search engines (50-60 chars)
   */
  metaTitle?: string | null;
  /**
   * Custom meta description for search engines (150-160 chars)
   */
  metaDescription?: string | null;
  keywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Open Graph title for social sharing
   */
  ogTitle?: string | null;
  /**
   * Open Graph description for social sharing
   */
  ogDescription?: string | null;
  /**
   * Open Graph image for social sharing
   */
  ogImage?: (number | null) | Media;
  /**
   * AI-assessed SEO quality score (0-100)
   */
  seoScore?: number | null;
  /**
   * Notes from last SEO review
   */
  seoNotes?: string | null;
  /**
   * When SEO was last reviewed
   */
  lastSeoReviewAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Post-publish SEO audits. One row per audit run; multiple rows per page over time form history. Operational data — no drafts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-audits".
 */
export interface PageAudit {
  id: number;
  pageType: 'service' | 'guide';
  service?: (number | null) | Service;
  guide?: (number | null) | Guide;
  priority: 'high' | 'medium' | 'low';
  status: 'new' | 'reviewed' | 'applied' | 'rejected';
  auditedAt: string;
  /**
   * Auto-filled from page slug + auditedAt — used as admin list title.
   */
  summaryTitle?: string | null;
  currentMetrics?: {
    impressions?: number | null;
    clicks?: number | null;
    /**
     * Decimal 0–1
     */
    ctr?: number | null;
    avgPosition?: number | null;
    dateRange?: {
      from?: string | null;
      to?: string | null;
    };
  };
  topQueries?:
    | {
        query: string;
        impressions?: number | null;
        clicks?: number | null;
        position?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Queries at positions 11–20 with meaningful impressions.
   */
  almostRankingQueries?:
    | {
        query: string;
        impressions?: number | null;
        position?: number | null;
        id?: string | null;
      }[]
    | null;
  competitors?:
    | {
        rank: number;
        url: string;
        title?: string | null;
        metaDescription?: string | null;
        id?: string | null;
      }[]
    | null;
  competitorAnalysis?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  proposedChanges?: {
    title?: string | null;
    metaDescription?: string | null;
    h1?: string | null;
    contentGaps?:
      | {
          gap: string;
          rationale?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Populated only when the skill runs with --lighthouse.
   */
  lighthouse?: {
    performance?: number | null;
    accessibility?: number | null;
    bestPractices?: number | null;
    seo?: number | null;
    runAt?: string | null;
  };
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  slug: string;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Custom page title for search engines (50-60 chars)
   */
  metaTitle?: string | null;
  /**
   * Custom meta description for search engines (150-160 chars)
   */
  metaDescription?: string | null;
  /**
   * Target SEO keywords (localized — different keywords per market)
   */
  keywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Open Graph title for social sharing
   */
  ogTitle?: string | null;
  /**
   * Open Graph description for social sharing
   */
  ogDescription?: string | null;
  /**
   * Open Graph image for social sharing
   */
  ogImage?: (number | null) | Media;
  /**
   * AI-assessed SEO quality score (0-100)
   */
  seoScore?: number | null;
  /**
   * Notes from last SEO review
   */
  seoNotes?: string | null;
  /**
   * When SEO was last reviewed
   */
  lastSeoReviewAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  services?: {
    /**
     * Allow clients to find services.
     */
    find?: boolean | null;
    /**
     * Allow clients to create services.
     */
    create?: boolean | null;
    /**
     * Allow clients to update services.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete services.
     */
    delete?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete categories.
     */
    delete?: boolean | null;
  };
  guides?: {
    /**
     * Allow clients to find guides.
     */
    find?: boolean | null;
    /**
     * Allow clients to create guides.
     */
    create?: boolean | null;
    /**
     * Allow clients to update guides.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete guides.
     */
    delete?: boolean | null;
  };
  landingPages?: {
    /**
     * Allow clients to find landing-pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create landing-pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update landing-pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete landing-pages.
     */
    delete?: boolean | null;
  };
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete pages.
     */
    delete?: boolean | null;
  };
  pageAudits?: {
    /**
     * Allow clients to find page-audits.
     */
    find?: boolean | null;
    /**
     * Allow clients to create page-audits.
     */
    create?: boolean | null;
    /**
     * Allow clients to update page-audits.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete page-audits.
     */
    delete?: boolean | null;
  };
  contentOpportunities?: {
    /**
     * Allow clients to find content-opportunities.
     */
    find?: boolean | null;
    /**
     * Allow clients to create content-opportunities.
     */
    create?: boolean | null;
    /**
     * Allow clients to update content-opportunities.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete content-opportunities.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
  };
  'payload-mcp-tool'?: {
    /**
     * Wipe all text content from services or guides while preserving media (logo, screenshot, videos), slugs, relationships, and structural fields. Use before re-running research/write pipeline to test from a clean slate. Resets contentPipelineStatus to not-started.
     */
    wipeContent?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'content-opportunities';
        value: number | ContentOpportunity;
      } | null)
    | ({
        relationTo: 'guides';
        value: number | Guide;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'page-audits';
        value: number | PageAudit;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  icon?: T;
  content?: T;
  metaTitle?: T;
  metaDescription?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  ogTitle?: T;
  ogDescription?: T;
  ogImage?: T;
  seoScore?: T;
  seoNotes?: T;
  lastSeoReviewAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-opportunities_select".
 */
export interface ContentOpportunitiesSelect<T extends boolean = true> {
  type?: T;
  priority?: T;
  status?: T;
  discoveredAt?: T;
  title?: T;
  targetKeyword?: T;
  locale?: T;
  estimatedMonthlyImpressions?: T;
  reasoning?: T;
  competitorUrls?:
    | T
    | {
        url?: T;
        title?: T;
        rank?: T;
        id?: T;
      };
  sourceQueries?:
    | T
    | {
        query?: T;
        impressions?: T;
        position?: T;
        id?: T;
      };
  redditSignals?:
    | T
    | {
        subreddit?: T;
        postUrl?: T;
        snippet?: T;
        date?: T;
        id?: T;
      };
  resultingType?: T;
  resultingService?: T;
  resultingGuide?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guides_select".
 */
export interface GuidesSelect<T extends boolean = true> {
  slug?: T;
  difficulty?: T;
  timeRequired?: T;
  date?: T;
  featuredOnHomepage?: T;
  contentPipelineStatus?: T;
  title?: T;
  category?: T;
  description?: T;
  sourceService?: T;
  targetService?: T;
  author?: T;
  missingFeatures?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  intro?: T;
  beforeYouStart?: T;
  steps?:
    | T
    | {
        title?: T;
        content?: T;
        video?: T;
        videoOrientation?: T;
        complete?: T;
        id?: T;
      };
  troubleshooting?: T;
  outro?: T;
  metaTitle?: T;
  metaDescription?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  ogTitle?: T;
  ogDescription?: T;
  ogImage?: T;
  seoScore?: T;
  seoNotes?: T;
  lastSeoReviewAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  category?: T;
  recommendedServices?: T;
  relatedService?: T;
  content?: T;
  metaTitle?: T;
  metaDescription?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  ogTitle?: T;
  ogDescription?: T;
  ogImage?: T;
  seoScore?: T;
  seoNotes?: T;
  lastSeoReviewAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-audits_select".
 */
export interface PageAuditsSelect<T extends boolean = true> {
  pageType?: T;
  service?: T;
  guide?: T;
  priority?: T;
  status?: T;
  auditedAt?: T;
  summaryTitle?: T;
  currentMetrics?:
    | T
    | {
        impressions?: T;
        clicks?: T;
        ctr?: T;
        avgPosition?: T;
        dateRange?:
          | T
          | {
              from?: T;
              to?: T;
            };
      };
  topQueries?:
    | T
    | {
        query?: T;
        impressions?: T;
        clicks?: T;
        position?: T;
        id?: T;
      };
  almostRankingQueries?:
    | T
    | {
        query?: T;
        impressions?: T;
        position?: T;
        id?: T;
      };
  competitors?:
    | T
    | {
        rank?: T;
        url?: T;
        title?: T;
        metaDescription?: T;
        id?: T;
      };
  competitorAnalysis?: T;
  proposedChanges?:
    | T
    | {
        title?: T;
        metaDescription?: T;
        h1?: T;
        contentGaps?:
          | T
          | {
              gap?: T;
              rationale?: T;
              id?: T;
            };
      };
  lighthouse?:
    | T
    | {
        performance?: T;
        accessibility?: T;
        bestPractices?: T;
        seo?: T;
        runAt?: T;
      };
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  content?: T;
  metaTitle?: T;
  metaDescription?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  ogTitle?: T;
  ogDescription?: T;
  ogImage?: T;
  seoScore?: T;
  seoNotes?: T;
  lastSeoReviewAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  region?: T;
  featured?: T;
  contentPipelineStatus?: T;
  name?: T;
  category?: T;
  location?: T;
  freeOption?: T;
  startingPrice?: T;
  description?: T;
  url?: T;
  affiliateUrl?: T;
  screenshot?: T;
  logo?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  pricingTiers?:
    | T
    | {
        name?: T;
        price?: T;
        billingNote?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  content?: T;
  issues?:
    | T
    | {
        issue?: T;
        id?: T;
      };
  recommendedAlternative?: T;
  researchStatus?: T;
  lastResearchedAt?: T;
  gdprCompliance?: T;
  gdprNotes?: T;
  privacyPolicyUrl?: T;
  pricingDetails?: T;
  pricingUrl?: T;
  headquarters?: T;
  parentCompany?: T;
  foundedYear?: T;
  employeeCount?: T;
  dataStorageLocations?:
    | T
    | {
        location?: T;
        id?: T;
      };
  certifications?:
    | T
    | {
        certification?: T;
        id?: T;
      };
  openSource?: T;
  sourceCodeUrl?: T;
  researchNotes?: T;
  sourceUrls?:
    | T
    | {
        url?: T;
        label?: T;
        id?: T;
      };
  userSentiment?:
    | T
    | {
        positive?: T;
        negative?: T;
        mixed?: T;
        summary?: T;
        lastUpdated?: T;
      };
  redditMentions?:
    | T
    | {
        subreddit?: T;
        postUrl?: T;
        postTitle?: T;
        sentiment?: T;
        snippet?: T;
        date?: T;
        id?: T;
      };
  recentNews?:
    | T
    | {
        source?: T;
        url?: T;
        title?: T;
        date?: T;
        summary?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  ogTitle?: T;
  ogDescription?: T;
  ogImage?: T;
  seoScore?: T;
  seoNotes?: T;
  lastSeoReviewAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  services?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  categories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  guides?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  landingPages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  pageAudits?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  contentOpportunities?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
      };
  'payload-mcp-tool'?:
    | T
    | {
        wipeContent?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}